const state={tab:'notices',items:[],editing:null};
const CONFIG={notices:{title:'공지',endpoint:'/api/admin/notices',fields:['title','content','tag','date','pinned','published']},events:{title:'일정',endpoint:'/api/admin/events',fields:['title','description','type','status','dateLabel','eventDate','published']},gallery:{title:'갤러리',endpoint:'/api/admin/gallery',fields:['title','description','category','imageUrl','thumbUrl','date','sortOrder','published']}};
const LABELS={title:'제목',content:'내용',tag:'태그',date:'날짜',pinned:'고정',published:'게시',description:'설명',type:'유형',status:'상태',dateLabel:'표시 날짜',eventDate:'실제 날짜',category:'카테고리',imageUrl:'이미지 URL',thumbUrl:'썸네일 URL',sortOrder:'정렬 순서'};
const $=(selector)=>document.querySelector(selector);
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
async function api(path,options={}){const response=await fetch(path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'요청에 실패했습니다.');return data;}
async function checkSession(){const session=await api('/api/admin/session');$('#login-panel').hidden=session.authenticated;$('#dashboard').hidden=!session.authenticated;if(session.authenticated)await loadItems();}
async function login(event){event.preventDefault();try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({password:$('#login-password').value})});$('#login-password').value='';$('#login-message').textContent='';await checkSession();}catch(error){$('#login-message').textContent=error.message;}}
async function logout(){await api('/api/admin/logout',{method:'POST'});state.items=[];state.editing=null;await checkSession();}
function setTab(tab){state.tab=tab;state.editing=null;document.querySelectorAll('[data-tab]').forEach((button)=>button.classList.toggle('active',button.dataset.tab===tab));loadItems();}
async function loadItems(){const config=CONFIG[state.tab];$('#list-title').textContent=`${config.title} 목록`;$('#form-title').textContent=`${config.title} 작성`;const result=await api(config.endpoint);state.items=result.items||[];renderList();renderForm(null);}
function renderList(){const list=$('#item-list');if(!state.items.length){list.innerHTML='<p class="admin-message">등록된 항목이 없습니다.</p>';return;}list.innerHTML=state.items.map((item)=>`<button class="item-button${state.editing?.id===item.id?' active':''}" type="button" data-id="${escapeHtml(item.id)}"><strong>${escapeHtml(item.title)}</strong><span>${escapeHtml(item.date||item.dateLabel||item.category||'')} · ${item.published===false?'비공개':'게시'}</span></button>`).join('');}
function renderForm(item){state.editing=item;const form=$('#cms-form');const config=CONFIG[state.tab];$('#form-title').textContent=`${config.title} ${item?'수정':'작성'}`;$('#delete-button').hidden=!item;form.innerHTML=config.fields.map((field)=>renderField(field,item)).join('')+(state.tab==='gallery'?renderUpload():'');$('#form-message').textContent='';renderList();}
function renderField(field,item){const value=item?.[field]??'';if(field==='published'||field==='pinned'){const checked=item?item[field]!==false&&item[field]!==0:field==='published';return `<label class="check-row"><input type="checkbox" name="${field}" ${checked?'checked':''}> ${LABELS[field]}</label>`;}if(field==='content'||field==='description')return `<label>${LABELS[field]}<textarea name="${field}">${escapeHtml(value)}</textarea></label>`;const type=field==='eventDate'?'date':field==='sortOrder'?'number':'text';return `<label>${LABELS[field]}<input type="${type}" name="${field}" value="${escapeHtml(value)}"></label>`;}
function renderUpload(){return '<div class="upload-row"><label>이미지 업로드<input id="upload-file" type="file" accept="image/jpeg,image/png,image/webp"></label><button type="button" class="secondary" id="upload-button">업로드</button></div>';}
function getFormPayload(){const form=$('#cms-form');const payload={};CONFIG[state.tab].fields.forEach((field)=>{const input=form.elements[field];if(!input)return;payload[field]=input.type==='checkbox'?input.checked:input.value.trim();});return payload;}
async function saveItem(event){event.preventDefault();const config=CONFIG[state.tab];const method=state.editing?'PUT':'POST';const url=state.editing?`${config.endpoint}/${encodeURIComponent(state.editing.id)}`:config.endpoint;try{await api(url,{method,body:JSON.stringify(getFormPayload())});$('#form-message').textContent='저장했습니다.';state.editing=null;await loadItems();}catch(error){$('#form-message').textContent=error.message;}}
async function deleteItem(){if(!state.editing||!confirm('정말 삭제할까요?'))return;await api(`${CONFIG[state.tab].endpoint}/${encodeURIComponent(state.editing.id)}`,{method:'DELETE'});state.editing=null;await loadItems();}
async function uploadImage(){const input=$('#upload-file');if(!input?.files?.[0])return;const body=new FormData();body.append('file',input.files[0]);const response=await fetch('/api/admin/upload',{method:'POST',body});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'업로드에 실패했습니다.');$('#cms-form').elements.imageUrl.value=result.imageUrl;$('#cms-form').elements.thumbUrl.value=result.imageUrl;}
function bindEvents(){$('#login-form').addEventListener('submit',login);$('#logout-button').addEventListener('click',logout);$('#new-button').addEventListener('click',()=>renderForm(null));$('#cancel-button').addEventListener('click',()=>renderForm(null));$('#delete-button').addEventListener('click',deleteItem);$('#cms-form').addEventListener('submit',saveItem);document.querySelectorAll('[data-tab]').forEach((button)=>button.addEventListener('click',()=>setTab(button.dataset.tab)));$('#item-list').addEventListener('click',(event)=>{const button=event.target.closest('[data-id]');if(!button)return;renderForm(state.items.find((item)=>item.id===button.dataset.id));});document.addEventListener('click',async(event)=>{if(event.target?.id!=='upload-button')return;try{await uploadImage();}catch(error){$('#form-message').textContent=error.message;}});}
bindEvents();checkSession().catch((error)=>{$('#login-message').textContent=error.message;});